# Generated by Django 4.0.2 on 2022-02-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_details',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
