# Generated by Django 4.0.2 on 2022-02-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0002_alter_register_details_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_details',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FSapp.register_details'),
        ),
    ]
