# Generated by Django 4.0.2 on 2022-03-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0002_remove_attendance_attendence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(choices=[('P', 'PRESENT'), ('A', 'ABSENT')], max_length=5, null=True),
        ),
    ]
