# Generated by Django 4.0.2 on 2022-03-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0003_alter_attendance_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='paid_on',
        ),
    ]
