# Generated by Django 4.0.2 on 2022-02-28 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0003_alter_health_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_details',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_details', to='FSapp.register_details'),
        ),
    ]
