# Generated by Django 4.0.2 on 2022-03-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0005_alter_appoinments_name_alter_diet_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medical_doubts',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='modelcomplaints',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
